.PHONY: install dev build lint up down

install:
	npm install
dev:
	npm run dev
build:
	npm run build
lint:
	npm run lint
up:
	docker compose -f ../compose.yaml up -d
down:
	docker compose -f ../compose.yaml down
