CREATE TABLE public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_number TEXT NOT NULL UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_of_birth DATE,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.customer_profiles (
  customer_id BIGINT PRIMARY KEY
    REFERENCES public.customers (id) ON DELETE CASCADE,
  preferred_language TEXT NOT NULL DEFAULT 'en',
  occupation TEXT,
  annual_income NUMERIC(14, 2),
  tax_residency_country CHAR(2),
  risk_rating TEXT NOT NULL DEFAULT 'standard'
    CHECK (risk_rating IN ('low', 'standard', 'high')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.customer_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL
    REFERENCES public.customers (id) ON DELETE CASCADE,
  address_type TEXT NOT NULL
    CHECK (address_type IN ('residential', 'mailing', 'work')),
  line_1 TEXT NOT NULL,
  line_2 TEXT,
  city TEXT NOT NULL,
  region TEXT,
  postal_code TEXT NOT NULL,
  country_code CHAR(2) NOT NULL,
  valid_from DATE NOT NULL DEFAULT CURRENT_DATE,
  valid_to DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (customer_id, address_type)
);

CREATE TABLE public.customer_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL
    REFERENCES public.customers (id) ON DELETE CASCADE,
  contact_type TEXT NOT NULL
    CHECK (contact_type IN ('email', 'mobile_phone', 'home_phone')),
  contact_value TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (customer_id, contact_type, contact_value)
);

CREATE UNIQUE INDEX customer_contacts_one_primary_per_type
  ON public.customer_contacts (customer_id, contact_type)
  WHERE is_primary;

CREATE TABLE public.customer_preferences (
  customer_id BIGINT PRIMARY KEY
    REFERENCES public.customers (id) ON DELETE CASCADE,
  marketing_email_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
  marketing_sms_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
  paperless_statements BOOLEAN NOT NULL DEFAULT TRUE,
  notification_channels JSONB NOT NULL DEFAULT '{"email": true, "sms": false}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION public.notify_customer_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  customer_id BIGINT;
  customer_number TEXT;
BEGIN
  customer_id := COALESCE(NEW.id, OLD.id);
  customer_number := COALESCE(NEW.customer_number, OLD.customer_number);
  PERFORM pg_notify('customer_changes', json_build_object('operation', TG_OP, 'id', customer_id, 'customer_number', customer_number, 'occurred_at', clock_timestamp())::TEXT);
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER customers_notify_changes
AFTER INSERT OR UPDATE OR DELETE ON public.customers
FOR EACH ROW EXECUTE FUNCTION public.notify_customer_change();

-- Child delete events need customer_id so Kafka Streams can remove the embedded row.
ALTER TABLE public.customer_addresses REPLICA IDENTITY FULL;
ALTER TABLE public.customer_contacts REPLICA IDENTITY FULL;
